2024-03-21 08:48:36.147 [info] (Client) Pylance async client (2024.2.2) started with python extension (2024.2.0)
2024-03-21 08:48:38.356 [info] [Info  - 08:48:38] (1882) Pylance language server 2024.2.2 (pyright version 1.1.348, commit cfb1de0c) starting
2024-03-21 08:48:38.358 [info] [Info  - 08:48:38] (1882) Server root directory: file:///home/pi/.vscode-server/extensions/ms-python.vscode-pylance-2024.2.2/dist
2024-03-21 08:48:38.359 [info] [Info  - 08:48:38] (1882) Starting service instance "basics"
2024-03-21 08:48:38.577 [info] [Info  - 08:48:38] (1882) Setting environmentName for service "basics": "C:\Users\Justin\Anaconda3\python.exe"
2024-03-21 08:48:39.173 [info] [Info  - 08:48:39] (1882) Found 19 source files
2024-03-21 08:48:40.913 [info] [Info  - 08:48:40] (1882) Background analysis(1) root directory: file:///home/pi/.vscode-server/extensions/ms-python.vscode-pylance-2024.2.2/dist
2024-03-21 08:48:40.924 [info] [Info  - 08:48:40] (1882) Background analysis(1) started
2024-03-21 08:48:41.664 [info] [Info  - 08:48:41] (1882) Indexer background runner(2) root directory: file:///home/pi/.vscode-server/extensions/ms-python.vscode-pylance-2024.2.2/dist (index)
2024-03-21 08:48:41.665 [info] [Info  - 08:48:41] (1882) Indexing(2) started
2024-03-21 08:48:47.198 [info] [Info  - 08:48:47] (1882) [BG(1)] Long operation: binding: file:///usr/lib/python3/dist-packages/numpy/__init__.py (3341ms)
2024-03-21 08:48:49.167 [info] [Info  - 08:48:49] (1882) [IDX(2)] Long operation: scan packages file:///home/pi/mxet300_lab/basics (7475ms)
2024-03-21 08:48:49.174 [info] [Info  - 08:48:49] (1882) scanned(2) 222 files over 1 exec env
2024-03-21 08:48:49.305 [info] [Info  - 08:48:49] (1882) [BG(1)] Long operation: checking: file:///home/pi/mxet300_lab/basics/Lab7Template.py (6196ms)
2024-03-21 08:48:49.306 [info] [Info  - 08:48:49] (1882) [BG(1)] Long operation: analyzing: file:///home/pi/mxet300_lab/basics/Lab7Template.py (7565ms)
2024-03-21 08:48:59.628 [info] [Info  - 08:48:59] (1882) [IDX(2)] Long operation: index execution environment file:///home/pi/mxet300_lab/basics (6240ms)
2024-03-21 08:48:59.709 [info] [Info  - 08:48:59] (1882) [IDX(2)] Long operation: index packages file:///home/pi/mxet300_lab/basics (6456ms)
2024-03-21 08:48:59.710 [info] [Info  - 08:48:59] (1882) indexed(2) 154 files over 1 exec env
2024-03-21 08:49:00.359 [info] [Info  - 08:49:00] (1882) Indexing finished(2).
2024-03-21 09:08:38.298 [info] [Info  - 09:08:38] (1882) [FG] Long operation: binding: file:///usr/lib/python3/dist-packages/numpy/__init__.py (2535ms)
2024-03-21 09:14:58.421 [info] [Info  - 09:14:58] (1882) Setting environmentName for service "basics": "C:\Users\Justin\Anaconda3\python.exe"
2024-03-21 09:14:58.586 [info] Traceback (most recent call last):
  File "<string>", line 1, in <module>
FileNotFoundError: [Errno 2] No such file or directory

2024-03-21 09:14:58.671 [info] Traceback (most recent call last):
  File "<string>", line 1, in <module>
OSError: [Errno 2] No such file or directory

2024-03-21 09:14:58.736 [info] [Info  - 09:14:58] (1882) Found 19 source files
2024-03-21 09:14:59.521 [info] Traceback (most recent call last):
  File "<string>", line 1, in <module>
FileNotFoundError: [Errno 2] No such file or directory

2024-03-21 09:14:59.619 [info] Traceback (most recent call last):
  File "<string>", line 1, in <module>
OSError: [Errno 2] No such file or directory

2024-03-21 09:15:38.756 [info] [Info  - 09:15:38] (1882) Setting environmentName for service "basics": "C:\Users\Justin\Anaconda3\python.exe"
2024-03-21 09:15:38.886 [info] Traceback (most recent call last):
  File "<string>", line 1, in <module>
FileNotFoundError: [Errno 2] No such file or directory

2024-03-21 09:15:38.948 [info] Traceback (most recent call last):
  File "<string>", line 1, in <module>
OSError: [Errno 2] No such file or directory

2024-03-21 09:15:38.992 [info] [Info  - 09:15:38] (1882) Found 19 source files
2024-03-21 09:15:39.088 [info] Traceback (most recent call last):
  File "<string>", line 1, in <module>
FileNotFoundError: [Errno 2] No such file or directory

2024-03-21 09:15:39.340 [info] Traceback (most recent call last):
  File "<string>", line 1, in <module>
OSError: [Errno 2] No such file or directory

